---
- hosts: all
  gather_facts: false
  tasks:
    - name: Setup root user, password 'foobar', create SSH key
      user:
        name: root
        password: "{{ 'foobar' | password_hash('sha512') }}"
        append: true
        group: wheel
        shell: /bin/bash
        update_password: always
        generate_ssh_key: true
    - name: Edit sshd_config file
      lineinfile:
        path: '/etc/ssh/sshd_config'
        state: present
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^PasswordAuthentication\s+no', line: 'PasswordAuthentication yes' }
        - { regexp: '^[#]*PubkeyAuthentication\s+yes', line: 'PubkeyAuthentication yes' }
        - { regexp: '^[#]*PermitRootLogin\s+yes', line: 'PermitRootLogin yes' }
    - name: Restart SSHd
      systemd:
        name: 'sshd'
        daemon_reload: yes
        state: restarted
    - name: Add EPEL repository
      yum_repository:
       name: epel
       description: EPEL YUM repo
       mirrorlist: https://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch
       enabled: yes
       gpgcheck: no
       keepalive: yes
    - name: Configure Gluster-Ansible sac repo
      yum_repository:
        name: "sac-gluster-ansible-epel-7"
        description: "Copr repo for gluster-ansible owned by sac"
        baseurl: "https://copr-be.cloud.fedoraproject.org/results/sac/gluster-ansible/epel-7-$basearch/"
        gpgkey: "https://copr-be.cloud.fedoraproject.org/results/sac/gluster-ansible/pubkey.gpg"
        keepalive: yes
    - name: Configure Gluster master nightly repo
      yum_repository:
        name: "gluster-nightly-master"
        description: "Gluster Nightly builds (master branch)"
        baseurl: "http://artifacts.ci.centos.org/gluster/nightly/master/$releasever/$basearch"
        gpgcheck: false
        keepalive: yes
- hosts: gluster_servers
  gather_facts: false
  tasks:
    - name: Install Gluster and additional packages on servers
      yum:
        name: ['policycoreutils-python', 'python-gluster-mgmt-client', 'glusterfs-server', 'glusterfs-fuse', 'glusterfs-api', 'samba-vfs-glusterfs', 'glusterfs-gnfs', 'samba-client']
        state: present
        update_cache: yes
      retries: 10
      delay: 5
    - name: Setup SELinux for Samba
      seboolean: name=samba_load_libgfapi state=yes persistent=yes
    - name: Setup SELinux in permissive mode
      selinux: policy=targeted state=enforcing
    - name: Setup Samba credentials
      shell: (echo "foobar"; echo "foobar") | smbpasswd -a root
    - name: Setup Samba configuration
      blockinfile:
        dest: /etc/samba/smb.conf
        insertafter: '\[global\]'
        content: |
          kernel share modes = no
          kernel oplocks = no
          map archive = no
          map hidden = no
          map read only = no
          map system = no
          store dos attributes = yes
    - name: Restart services
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        state: restarted
      with_items:
       - 'glusterd'
       - 'smb'
       - 'rpcbind'
- hosts: node-0
  gather_facts: false
  tasks:
    - name: Install Gluster-ansible and additional packages on client
      yum:
        name: ['gluster-ansible-roles', 'sshpass', 'glusterfs-fuse', 'samba-client']
        state: present
        update_cache: yes
      retries: 10
      delay: 5
    - name: distribute SSH key
      command: "{{ item }}"
      with_sequence: start=0 end=4 format="sshpass -p foobar ssh-copy-id -f -o StrictHostKeyChecking=no root@node-%01x"
